<?php

/**
 * @file
 * Contains webform_rest_handler.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function webform_rest_handler_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the webform_rest_handler module.
    case 'help.page.webform_rest_handler':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Webform CRM/REST component functionality for CBS.') . '</p>';
      return $output;

    default:
  }
}

/******************************************************************************/
// Theme hooks.
/******************************************************************************/

/**
 * Implements hook_theme().
 */
function webform_rest_handler_theme() {
  $info = [
    'webform_handler_rest_service_summary' => [
      'variables' => ['settings' => NULL, 'handler' => NULL],
    ],
  ];

  return $info;
}
